server:
  port: 8080
  servlet:
    context-path: "/api"

spring:
  application:
    name: UserLogin

mybatis-plus:
  configuration:
    # 日志的输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
