create table user
(
    id            bigint auto_increment comment '主键'
        primary key,
    user_name     varchar(256)                                                                                                                                                                                                                                                                                                                                                                                                                             null comment '昵称',
    user_account  varchar(1024)                                                                                                                                                                                                                                                                                                                                                                                                                            null comment '登录账号',
    avatar_url    varchar(1024) default 'https://cn.bing.com/images/search?view=detailV2&ccid=b39hvvD0&id=59AFEC50707AD1876BBA7BF097235ABE6D08D8CE&thid=OIP.b39hvvD0k83rsxpCvwWf7QHaQC&mediaurl=https%3a%2f%2fwww.qqkw.com%2fd%2ffile%2fp%2f2018%2f05-17%2f0515954b9ce3b4eee4774a73406ed5b6.jpg&exph=2436&expw=1125&q=%e7%be%8e%e5%a5%b3&simid=608029664401501925&FORM=IRPRST&ck=267CEEC34F81BA311B234C292FF199DC&selectedIndex=0&qpvt=%e7%be%8e%e5%a5%b3' null comment '头像',
    sex           tinyint       default 0                                                                                                                                                                                                                                                                                                                                                                                                                  null comment '性别',
    user_password varchar(100)                                                                                                                                                                                                                                                                                                                                                                                                                             null comment '密码',
    phone         varchar(50)                                                                                                                                                                                                                                                                                                                                                                                                                              null comment '电话',
    email         varchar(32)                                                                                                                                                                                                                                                                                                                                                                                                                              null comment '邮箱',
    user_status   int           default 0                                                                                                                                                                                                                                                                                                                                                                                                                  not null comment '用户的状态 0 -> 正常 1 -> 账号被禁用',
    create_time   datetime      default CURRENT_TIMESTAMP                                                                                                                                                                                                                                                                                                                                                                                                  null,
    update_time   datetime      default CURRENT_TIMESTAMP                                                                                                                                                                                                                                                                                                                                                                                                  null on update CURRENT_TIMESTAMP,
    is_delete     int           default 0                                                                                                                                                                                                                                                                                                                                                                                                                  not null comment '逻辑删除 0->未删除 1->已删除',
    is_admin      int           default 0                                                                                                                                                                                                                                                                                                                                                                                                                  not null comment '是否是管理员 0->普通用户 1->管理员',
    planet_code   varchar(32)                                                                                                                                                                                                                                                                                                                                                                                                                              null comment '编号',
    constraint user_account
        unique (user_account)
);
